Repository panel-attack/panel-attack, pull requests merged in 2021-12, with the labels that each got.

#310 Make 2P telegraph show up on right side
  engine.lua
Labels: bug, enhancement, Client-side

#312 Make more room for the spectator list
  mainloop.lua
  theme.lua
Labels: Client-side, low-ish priority

#311 Asymmetrical portrait support
  character.lua
  graphics.lua
  readme_characters.txt
Labels: Client-side

#316 Fix potential crash
  engine.lua
Labels: bug, Client-side

#315 Default VSync to off
  globals.lua
  options.lua
Labels: Client-side

#309 Changes to rating display to use the highest rating
  mainloop.lua
Labels: Client-side

#330 Play Select Sound when tapping on menus
  click_menu.lua
  main.lua
  mainloop.lua
Labels: Client-side

#329 Fully play sound effects when transitioning
  engine.lua
  mainloop.lua
Labels: Client-side

#342 Reduce log output on client
  character.lua
  engine.lua
  logger.lua
  main.lua
  mainloop.lua
  network.lua
  panels.lua
  select_screen.lua
  sound.lua
  stage.lua
Labels: Client-side, Cleanup

#343 Bug Fix: defaultname pattern check
  server.lua
Labels: bug, Server-side, high priority
