Repository panel-attack/panel-attack, pull requests merged in 2021-11, with the labels that each got.

#244 Anti-Cheating Patch
  server.lua
Labels: Server-side

#246 Topped out animations
  engine.lua
Labels: enhancement, Client-side

#252 Patch: "You are all alone in the lobby" Bug
  mainloop.lua
Labels: bug, Client-side

#243 Replay file compression
  mainloop.lua
  save.lua
  server.lua
  util.lua
Labels: Server-side, Client-side, engine

#255 Change APM to disregard DAS
  engine.lua
Labels: bug, Client-side, low-ish priority

#260 Fix going away
  mainloop.lua
Labels: bug, Client-side

#262 Changing Display Name of Server
  mainloop.lua
Labels: Client-side, low-ish priority

#261 Better MultiBar Stop Time Indication
  graphics.lua
Labels: enhancement, Client-side

#259 Create BattleRoom class to reduce code duplication
  BattleRoom.lua
  click_menu.lua
  engine.lua
  game.lua
  globals.lua
  graphics_util.lua
  main.lua
  mainloop.lua
  options.lua
  replay_browser.lua
  select_screen.lua
  theme.lua
Labels: Client-side

#270 Support HD combo / chain cards
  graphics.lua
Labels: enhancement, Client-side

#268 Show ratings in the lobby
  mainloop.lua
  themes/Panel Attack/leagues/01_Bronze.png
  themes/Panel Attack/leagues/02_Silver.png
  themes/Panel Attack/leagues/03_Gold.png
  themes/Panel Attack/leagues/04_Platinum.png
  themes/Panel Attack/leagues/05_Diamond.png
  themes/Panel Attack/leagues/06_Master.png
  themes/Panel Attack/leagues/07_Grandmaster.png
Labels: enhancement, Client-side

#269 Fix server queue pop and add tests
  ServerQueueTests.lua
  consts.lua
  globals.lua
  mainloop.lua
  server_queue.lua
Labels: bug, Client-side

#266 Love 12 Support
  characters/__default/icon.png
  characters/__default/portrait.png
  graphics_util.lua
  stages/__default/background.png
  stages/__default/thumbnail.png
  themes/Panel Attack/background/readme.png
  themes/Panel Attack/background/select_screen.png
  themes/Panel Attack/level/level_cursor.png
  themes/Panel Attack/loading.png
  themes/Panel Attack/p1.png
  themes/Panel Attack/p2.png
  themes/Panel Attack/pause.png
  themes/Panel Attack/random_character.png
  themes/Panel Attack/random_stage.png
Labels: bug, Client-side

#253 Patch: Spectator Room Bug
  server.lua
Labels: bug, Server-side, high priority

#280 Return user to main menu instead of crashing game
  mainloop.lua
  network.lua
Labels: enhancement, Client-side

#275 Spectator list pos fix
  theme.lua
Labels: enhancement, Client-side

#281 Don't restore lobby selection if the lobby menu is new
  mainloop.lua
  network.lua
Labels: Client-side

#287 Removal of the win counter in 1pvs
  match.lua
Labels: Client-side, low-ish priority

#286 Placement Match Count Change
  server_globals.lua
Labels: Server-side

#284 Removed love.touchpressed
  click_menu.lua
Labels: bug, Client-side

#295 Changes in Prep for CPU
  StackTests.lua
  V3PdP source/Game.vc
  V3PdP source/engine before emulation of the crazy bug.vc
  V3PdP source/engine.vc
  V3PdP source/graphics.vc
  V3PdP source/input.vc
  V3PdP source/sound.vc
  V3PdP source/stage.vc
  V3PdP source/stage_Lakitu.vc
  V3PdP source/stage_Yoshi.vc
  V3PdP source/system.vc
  V3PdP source/title.vc
  engine.lua
  gen_panels.lua
  globals.lua
  graphics.lua
  main.lua
  mainloop.lua
  match.lua
  network.lua
  readme_replays.txt
  readme_themes.txt
  select_screen.lua
Labels: Client-side, Cleanup

#288 Removal of printing every time a frame is dropped
  mainloop.lua
Labels: Client-side

#300 Name Length Cap
  mainloop.lua
Labels: Client-side

#301 Chain puzzles
  Puzzle.lua
  PuzzleSet.lua
  default_data/puzzles/stock (example).json
  engine.lua
  game.lua
  graphics.lua
  main.lua
  mainloop.lua
  puzzles.lua
  readme_puzzles.txt
  save.lua
Labels: enhancement, Client-side
