Repository panel-attack/panel-attack, pull requests merged in 2022-03, with the labels that each got.

#446 change to 32 bit dll file
  rich_presence/discord-rpc.dll
Labels: Client-side

#450 Add Screenshots to the game
  input.lua
Labels: enhancement, Client-side

#454 Remove debug rollback code
  match.lua
Labels: enhancement, Client-side

#453 Cleanup and improve panel generation
  csprngTests.lua
  engine.lua
  gen_panels.lua
  mainloop.lua
  server.lua
  server.py
Labels: Server-side, Client-side, engine

#452 Options Touch Menu
  analytics.lua
  globals.lua
  options.lua
Labels: enhancement, Client-side

#449 Illegal Garbage
  AttackEngine.lua
  character.lua
  engine.lua
  engine/GarbageQueue.lua
  engine/telegraph.lua
  logger.lua
  mainloop.lua
  select_screen.lua
Labels: enhancement, Client-side, engine

#456 Fix Compulsory Evacuation Device Bug
  engine/telegraph.lua
Labels: bug, Client-side

#458 Fix crash when clicking on music test
  options.lua
Labels: bug, Client-side

#457 Fix end phase desync
  engine.lua
  match.lua
Labels: bug, Client-side, engine

#459 Server Reports Directory
  main.lua
  server_file_io.lua
Labels: Server-side, Client-side, low-ish priority, Cleanup

#463 Fix rollback breaks
  engine.lua
  engine/GarbageQueue.lua
  engine/telegraph.lua
  match.lua
Labels: Client-side, engine

#464 New Seed Gen method
  conf.lua
  gen_panels.lua
Labels: Client-side, engine

#465 Fix crash
  gen_panels.lua
  select_screen.lua
Labels: bug, Client-side, engine

#466 lag improvements
  engine.lua
  globals.lua
  localization.csv
  main.lua
  mainloop.lua
  match.lua
  network.lua
  select_screen.lua
  theme.lua
  themes/Panel Attack/bug.png
Labels: Client-side

#472 Actually change vsync when toggled in options
  options.lua
Labels: bug, Client-side

#478 Change timer display from frames to milliseconds
  util.lua
Labels: enhancement, Client-side

#477 Fix critical chain stop time
  engine.lua
Labels: bug, Client-side, engine
