Repository panel-attack/panel-attack, pull requests merged in 2022-02, with the labels that each got.

#408 Compression optimizations
  select_screen.lua
  util.lua
Labels: enhancement, Client-side, Cleanup

#412 Table functions
  character.lua
  consts.lua
  graphics_util.lua
  main.lua
  mainloop.lua
  match.lua
  options.lua
  panels.lua
  select_screen.lua
  stage.lua
  table_util.lua
  table_util_tests.lua
  util.lua
Labels: Client-side, Cleanup

#420 Fix crash using on screen controls
  click_menu.lua
Labels: bug, Client-side

#416 Cleanup name change
  localization.csv
  mainloop.lua
Labels: enhancement, Client-side

#410 Send player ratings and seed from the server
  mainloop.lua
  server.lua
Labels: enhancement, Server-side, Client-side

#417 Don't allow using a name thats already in use
  server.lua
Labels: enhancement, Server-side

#419 Remove the alpha tags from autoupdater
  CreateAlphaLoveFile.ps1
  auto_updater/_config.lua
  auto_updater/main.lua
Labels: Client-side, Cleanup

#421 Audit server logs
  server.lua
Labels: Server-side, Cleanup

#415 Basic rich presence
  game.lua
  main.lua
  mainloop.lua
  match.lua
  rich_presence/README.md
  rich_presence/RichPresence.lua
  rich_presence/discord-rpc.dll
  rich_presence/discordRPC.lua
Labels: enhancement, Client-side

#423 Error Reports
  main.lua
  network.lua
  server.lua
  server_file_io.lua
Labels: enhancement, Server-side, Client-side

#424 Gracefully log out of server from game close
  main.lua
Labels: enhancement, Client-side

#434 Prepare to unify all the powershell file names
  CreateLoveFile.ps1
Labels: Client-side, Cleanup

#431 Compress Server Replays by Default
  server_globals.lua
Labels: Server-side, engine

#435 Adds 1-wide and 2-wide images
  characters/__default/telegraph/1-wide.png
  characters/__default/telegraph/2-wide.png
Labels: enhancement, Client-side

#430 Force garbage sizes
  mainloop.lua
Labels: Client-side, low-ish priority

#432 Scale images for telegraph
  engine/telegraph.lua
Labels: enhancement, Client-side
