Repository panel-attack/panel-attack, pull requests merged in 2022-01, with the labels that each got.

#344 Server Login Timestamps
  server.lua
  server_file_io.lua
Labels: enhancement, Server-side

#348 Fix Self Spectate bug
  mainloop.lua
Labels: bug, Client-side

#349 Add Server Logging and Compression Toggle
  server README.txt
  server.lua
  server_globals.lua
Labels: Server-side, high priority, Cleanup

#331 Flexible input configuration
  click_menu.lua
  config_inputs.lua
  engine.lua
  game.lua
  globals.lua
  input.lua
  localization.csv
  main.lua
  mainloop.lua
  match.lua
  network.lua
  options.lua
  replay_browser.lua
  save.lua
  select_screen.lua
Labels: enhancement, Client-side

#353 Enable Data Module
  auto_updater/conf.lua
  conf.lua
Labels: Client-side, low-ish priority, Cleanup

#355 Fix themes without config files
  theme.lua
Labels: bug, Client-side

#357 Don't crash when joystick ID is gone
  StackTests.lua
  input.lua
Labels: bug, Client-side

#365 Show more info upon crashing
  conf.lua
  main.lua
Labels: enhancement, Client-side

#374 Fix the winning player to use player_number
  BattleRoom.lua
Labels: bug, Client-side

#372 Allow using the fixed keys in 1 player modes, also added comments
  input.lua
Labels: Client-side

#366 Pause game if window becomes unfocused
  mainloop.lua
Labels: enhancement, Client-side

#358 Mainloop and Replay Cleanup
  BattleRoom.lua
  StackTests.lua
  click_menu.lua
  engine.lua
  globals.lua
  graphics.lua
  input.lua
  localization.csv
  main.lua
  mainloop.lua
  match.lua
  network.lua
  options.lua
  replay_browser.lua
  select_screen.lua
Labels: enhancement, Client-side

#375 Training Mode
  engine.lua
  globals.lua
  mainloop.lua
Labels: enhancement, Client-side, engine

#376 Provide an attack engine to clean up training mode and support future…
  AttackEngine.lua
  BattleRoom.lua
  engine.lua
  globals.lua
  graphics.lua
  main.lua
  mainloop.lua
  match.lua
  select_screen.lua
Labels: enhancement, Client-side

#384 Hide 1pvs scores in training mode
  select_screen.lua
Labels: bug, Client-side

#388 Start the timer immediately if there is no countdown
  engine.lua
Labels: Client-side

#387 Add new localizations, fix Japanese click menu font
  click_menu.lua
  graphics_util.lua
  localization.csv
  localization.lua
  mainloop.lua
Labels: Client-side

#393 Ensure APM/GPM value updates when replays are using fastforward
  graphics.lua
Labels: bug, Client-side

#398 Change alpha to beta
  CreateBetaLoveFile.ps1
  auto_updater/_config.lua
  auto_updater/main.lua
Labels: Client-side
