Repository panel-attack/panel-attack, pull requests merged in 2022-08, with the labels that each got.

#567 Modern Resolution Support
  UpdatingImage.lua
  character.lua
  click_menu.lua
  conf.lua
  config.lua
  engine.lua
  game.lua
  graphics.lua
  graphics_util.lua
  localization.csv
  main.lua
  mainloop.lua
  options.lua
  panels.lua
  stage.lua
  theme.lua
Labels: enhancement, Client-side

#576 Added input system that doesn't depend on variable step
  Puzzle.lua
  character.lua
  consts.lua
  engine.lua
  graphics_util.lua
  input.lua
  inputManager.lua
  joystickManager.lua
  main.lua
  mainloop.lua
  panels.lua
  select_screen/select_screen.lua
  stage.lua
  tableUtils.lua
  tableUtilsTest.lua
  table_util.lua
  table_util_tests.lua
  util.lua
Labels: high priority, Cleanup

#579 Added entry point for vs CPU mode
  computerPlayers/DummyCpu/DummyCpu.lua
  computerPlayers/computerPlayer.lua
  computerPlayers/computerPlayer.md
  developer.lua
  main.lua
  mainloop.lua
  match.lua
  select_screen/select_screen.lua
Labels: Client-side

#581 Cleanup graphics to support higher scaled images
  csprngTests.lua
  engine.lua
  engine/telegraph.lua
  graphics.lua
  graphics_util.lua
  mainloop.lua
  readme_themes.txt
  theme.lua
  themes/Panel Attack/cursor1.png
  themes/Panel Attack/cursor2.png
Labels: Client-side, graphics

#640 Remove .DS_Store files
  mainloop.lua
  save.lua
Labels: Client-side, Cleanup

#641 Fix filter error
  graphics_util.lua
Labels: bug, Client-side, high priority, graphics

#649 Spectator Hotfix #2
  select_screen/netplay.md
  select_screen/select_screen.lua
Labels: high priority

#648 Fix blurry graphics
  engine.lua
  game.lua
  graphics_util.lua
  main.lua
  panels.lua
Labels: Client-side, graphics
