Repository panel-attack/panel-attack, pull requests merged in 2022-05, with the labels that each got.

#498 Show Basic System info
  options.lua
Labels: enhancement, Client-side

#497 Improved Endless, Puzzles, and Time Attack
  Puzzle.lua
  StackTests.lua
  click_menu.lua
  engine.lua
  localization.csv
  mainloop.lua
  options.lua
  replay_browser.lua
  save.lua
  select_screen.lua
  server.lua
  theme.lua
Labels: enhancement, Client-side

#500 Custom Fonts
  localization.lua
  options.lua
  readme_themes.txt
  theme.lua
  themes/Panel Attack/config.json
Labels: enhancement, Client-side, low-ish priority

#512 Update the telegraph message in prep for update
  localization.csv
Labels: Client-side

#524 Give a warning when using love 11.3
  localization.csv
  mainloop.lua
Labels: Client-side

#526 Prevent Bad Image Crashes
  graphics_util.lua
  themes/Panel Attack/transparent.png
Labels: bug, Client-side

#510 Title Screen and scrolling background support
  StackTests.lua
  UpdatingImage.lua
  click_menu.lua
  config_inputs.lua
  consts.lua
  engine.lua
  globals.lua
  graphics.lua
  graphics_util.lua
  localization.csv
  logger.lua
  main.lua
  mainloop.lua
  options.lua
  select_screen.lua
  stage.lua
  theme.lua
  themes/Panel Attack/background/main.png
  themes/Panel Attack/background/readme.png
  themes/Panel Attack/background/select_screen.png
  themes/Panel Attack/background/title.png
  themes/Panel Attack/config.json
  themes/Panel Attack/leagues/00_Copper.png
  themes/Panel Attack/leagues/01_Bronze.png
Labels: enhancement, Client-side

#529 Fix loading in stages with no background
  mainloop.lua
  stage.lua
  stages/__default/background.png
Labels: bug, Client-side

#532 Popfx option bug fix
  options.lua
Labels: bug, Client-side

#519 Custom Training Modes
  AttackEngine.lua
  default_data/training/__examples/ChainMultiplyExample.json
  default_data/training/__examples/ChainTableExample.json
  default_data/training/__examples/ComboExample.json
  default_data/training/armageddon.json
  default_data/training/bronze.json
  engine/GarbageQueue.lua
  engine/telegraph.lua
  globals.lua
  main.lua
  mainloop.lua
  options.lua
  readme_training.txt
  save.lua
  select_screen.lua
Labels: enhancement, Client-side, engine
