Repository panel-attack/panel-attack, pull requests merged in 2022-06, with the labels that each got.

#536 Temp fix for mac crash
  save.lua
Labels: bug, Client-side

#538 Show deprecated message
  developer.lua
  localization.csv
  mainloop.lua
Labels: Client-side

#540 Fix bug where basic training modes crash
  mainloop.lua
Labels: bug, Client-side, high priority

#537 Allow touches on title screen
  mainloop.lua
Labels: Client-side

#543 Fix basic training bug
  mainloop.lua
Labels: bug, Client-side

#552 Limit Training Mode Garbage Queue
  AttackEngine.lua
  select_screen.lua
Labels: bug, enhancement, Client-side, engine

#557 Fix option index after returning from about menu
  options.lua
Labels: bug, Client-side

#547 Fix Broken Stage Images
  UpdatingImage.lua
  theme.lua
Labels: bug, Client-side

#548 Scale cursor image
  graphics.lua
Labels: enhancement, Client-side

#504 Clear puzzle
  Puzzle.lua
  engine.lua
  graphics.lua
  readme_puzzles.txt
  save.lua
Labels: enhancement, Client-side

#561 Add super select for PdP/TA characters
  default_data/characters/blargg/config.json
  default_data/characters/bowser/config.json
  default_data/characters/bumpty/config.json
  default_data/characters/dragon/config.json
  default_data/characters/elias/config.json
  default_data/characters/flare/config.json
  default_data/characters/froggy/config.json
  default_data/characters/hookbill/config.json
  default_data/characters/kamek/config.json
  default_data/characters/lakitu/config.json
  default_data/characters/lip/config.json
  default_data/characters/lungefish/config.json
  default_data/characters/navalpiranha/config.json
  default_data/characters/neris/config.json
  default_data/characters/phoenix/config.json
  default_data/characters/poochy/config.json
  default_data/characters/raphael/config.json
  default_data/characters/ruby/config.json
  default_data/characters/seren/config.json
  default_data/characters/sherbet/config.json
  default_data/characters/thanatos/config.json
  default_data/characters/thiana/config.json
  default_data/characters/wiggler/config.json
  default_data/characters/windy/config.json
Labels: enhancement, Client-side

#562 Clear puzzle hotfix
  Puzzle.lua
  PuzzleTests.lua
  engine.lua
Labels: bug, Client-side, engine

#560 rewrote leaderboard loop using ipairs and set rank by username comparison
  mainloop.lua
Labels: Client-side, Cleanup

#556 Preserve color for puzzles upon failure
  engine.lua
  mainloop.lua
Labels: enhancement, Client-side

#493 Refactor select screen
  globals.lua
  main.lua
  mainloop.lua
  match.lua
  select_screen.lua
  select_screen/netplay.md
  select_screen/select_screen.lua
  select_screen/select_screen_graphics.lua
  table_util.lua
Labels: Client-side, Cleanup
